defaults: &defaults
    docker:
      - image: circleci/android:api-28
        environment:
          CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
          CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
          GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx6144M -XX:MaxPermSize=1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError"'

version: 2
jobs:
  test:
    <<: *defaults
    resource_class: large

    steps:
      - checkout

      - run:
          name: Create Directory
          command:  mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - restore_cache:
          key: gradle-cache-v1-{{ checksum "build.gradle" }}

      - run:
          name: Download Android Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-v1-{{ checksum "build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew test

      - store_test_results:
          path: /tmp/circleci-test-results

      - store_artifacts:
          path: /tmp/circleci-artifacts

  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: gradle-cache-v1-{{ checksum "build.gradle" }}

      - run:
          name: Build release package
          command: ./gradlew assembleRelease

      - run:
          name: Link release directory
          command: ln -s `pwd`/build/outputs/aar/project-release.aar `pwd`/build/outputs/aar/$CIRCLE_PROJECT_REPONAME-release.aar

      - run:
          name: Deploy to Bintray
          command: ./gradlew bintrayUpload

workflows:
  version: 2
  test-n-deploy:
    jobs:
      # Execute job for all branches, and all tags.
      - test:
          filters:
            tags:
              only: /.*/

      # Execute job for no branches, and all tags
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/